#!/usr/bin/env bash
# shellcheck disable=SC1010
rm -rf jar bundle
mkdir jar
bnd copy https://repo.maven.apache.org/maven2/javax/activation/activation/1.1.1/activation-1.1.1.jar \
  jar/javax.activation-1.1.1.jar
bnd print --uses jar/javax.activation-1.1.1.jar
bnd jar/javax.activation-1.1.1.jar
mkdir bundle
bnd javax.activation.bnd
ls bundle
bnd bundle/javax.activation.jar
rm bundle/**
bnd do --output bundle javax.activation.bnd
ls bundle
bnd bundle/javax.activation.jar
bnd copy --strip https://repo.maven.apache.org/maven2/com/sun/mail/javax.mail/1.5.2/javax.mail-1.5.2.jar \
  jar/javax.mail-1.5.2.jar
bnd print --uses jar/javax.mail-1.5.2.jar
bnd javax.mail.bnd
bnd print -i javax.mail.jar
